export type CatalogGroup = { group: string; items: string[] };

export const symptoms: CatalogGroup[] = [
  {
    group: "Fever",
    items: [
      "Low-grade fever",
      "High-grade fever",
      "Acute fever",
      "Prolonged fever",
      "Intermittent fever",
      "Continuous fever",
      "Fever with chills or rigors",
      "Fever with rash",
      "Fever with joint pain",
      "Fever after travel",
      "Fever with bleeding",
      "Fever of unknown origin",
    ],
  },
  {
    group: "Respiratory",
    items: [
      "Dry cough",
      "Productive cough",
      "Cough with blood",
      "Sore throat",
      "Runny nose",
      "Nasal congestion",
      "Sneezing",
      "Shortness of breath",
      "Wheezing",
      "Chest tightness",
      "Pleuritic chest pain",
      "Noisy breathing",
    ],
  },
  {
    group: "Gastrointestinal",
    items: [
      "Nausea",
      "Vomiting",
      "Blood in vomit",
      "Loose stools",
      "Blood in stool",
      "Constipation",
      "Acidity or heartburn",
      "Bloating",
      "Generalised abdominal pain",
      "Upper abdominal pain",
      "Lower abdominal pain",
      "Loss of appetite",
      "Difficulty swallowing",
      "Jaundice",
    ],
  },
  {
    group: "Neurological",
    items: [
      "Headache",
      "Migraine-type headache",
      "Dizziness",
      "Vertigo",
      "Fainting",
      "Seizure",
      "Weakness of limb",
      "Numbness or tingling",
      "Tremor",
      "Confusion",
      "Memory concern",
      "Difficulty speaking",
      "Unsteady gait",
    ],
  },
  {
    group: "Cardiovascular",
    items: [
      "Chest pain",
      "Palpitations",
      "Breathlessness on exertion",
      "Breathlessness when lying flat",
      "Leg swelling",
      "Fainting on exertion",
      "Reduced exercise tolerance",
      "Cold extremities",
    ],
  },
  {
    group: "Urinary and genital",
    items: [
      "Burning urination",
      "Frequent urination",
      "Urgent urination",
      "Blood in urine",
      "Reduced urine output",
      "Flank pain",
      "Urinary incontinence",
      "Vaginal discharge",
      "Abnormal vaginal bleeding",
      "Pelvic pain",
      "Scrotal pain or swelling",
    ],
  },
  {
    group: "Musculoskeletal",
    items: [
      "Back pain",
      "Neck pain",
      "Joint pain",
      "Joint swelling",
      "Morning stiffness",
      "Muscle pain",
      "Muscle cramps",
      "Restricted movement",
      "Recent injury",
      "Heel pain",
    ],
  },
  {
    group: "Skin and allergy",
    items: [
      "Itching",
      "Localised rash",
      "Generalised rash",
      "Hives",
      "Facial swelling",
      "Skin wound",
      "Boil or abscess",
      "Pigmentation change",
      "Hair loss",
      "Nail change",
      "Insect bite",
    ],
  },
  {
    group: "ENT and eye",
    items: [
      "Ear pain",
      "Ear discharge",
      "Reduced hearing",
      "Tinnitus",
      "Sinus pressure",
      "Hoarseness",
      "Mouth ulcer",
      "Toothache",
      "Red eye",
      "Eye discharge",
      "Blurred vision",
      "Eye pain",
    ],
  },
  {
    group: "General and constitutional",
    items: [
      "Fatigue",
      "General weakness",
      "Body ache",
      "Unintentional weight loss",
      "Weight gain",
      "Night sweats",
      "Sleep disturbance",
      "Excessive thirst",
      "Excessive hunger",
      "Anxiety symptoms",
      "Low mood",
      "Reduced activity",
    ],
  },
  {
    group: "Paediatric presentations",
    items: [
      "Poor feeding",
      "Excessive crying",
      "Lethargy",
      "Delayed milestone concern",
      "Failure to gain weight",
      "Febrile seizure",
      "Fast breathing in child",
      "Diarrhoea in child",
      "Vomiting in child",
      "Rash in child",
    ],
  },
  {
    group: "Urgent red flags",
    items: [
      "Severe breathing difficulty",
      "Central chest pressure",
      "New facial droop",
      "Sudden limb weakness",
      "Altered consciousness",
      "Severe dehydration",
      "Uncontrolled bleeding",
      "Anaphylaxis symptoms",
      "Severe abdominal pain",
      "Suicidal thoughts",
    ],
  },
];

export const findings: CatalogGroup[] = [
  {
    group: "General examination",
    items: [
      "Alert and oriented",
      "Drowsy but arousable",
      "Febrile",
      "Afebrile",
      "Mild dehydration",
      "Moderate dehydration",
      "Severe dehydration",
      "Pallor present",
      "Icterus present",
      "Cyanosis present",
      "Clubbing present",
      "Pedal edema present",
      "Lymph nodes palpable",
    ],
  },
  {
    group: "ENT and oral",
    items: [
      "Throat congestion",
      "Tonsillar enlargement",
      "Tonsillar exudate",
      "Nasal mucosal edema",
      "Sinus tenderness",
      "Ear canal inflammation",
      "Tympanic membrane congested",
      "Oral ulcers",
      "Dental caries",
      "Dry oral mucosa",
    ],
  },
  {
    group: "Respiratory",
    items: [
      "No respiratory distress",
      "Air entry equal bilaterally",
      "Reduced air entry",
      "Vesicular breath sounds",
      "Crepitations",
      "Rhonchi",
      "Wheeze present",
      "Bronchial breath sounds",
      "Accessory muscle use",
      "Chest wall tenderness",
    ],
  },
  {
    group: "Cardiovascular",
    items: [
      "Heart sounds normal",
      "Regular rhythm",
      "Tachycardia",
      "Bradycardia",
      "Irregular rhythm",
      "Murmur heard",
      "Raised JVP",
      "Peripheral pulses palpable",
      "Peripheral pulses feeble",
      "Capillary refill prolonged",
    ],
  },
  {
    group: "Abdomen",
    items: [
      "Soft and non-tender",
      "Generalised tenderness",
      "Epigastric tenderness",
      "Right upper quadrant tenderness",
      "Right iliac fossa tenderness",
      "Guarding present",
      "Rebound tenderness",
      "Bowel sounds present",
      "Organomegaly present",
      "Ascites present",
    ],
  },
  {
    group: "Neurological",
    items: [
      "Higher functions normal",
      "Cranial nerves grossly normal",
      "No focal neurological deficit",
      "Motor power reduced",
      "Sensory deficit present",
      "Reflexes normal",
      "Neck stiffness present",
      "Cerebellar signs present",
      "Gait normal",
      "Gait unsteady",
    ],
  },
  {
    group: "Musculoskeletal",
    items: [
      "Local tenderness",
      "Swelling present",
      "Range of motion full",
      "Range of motion restricted",
      "Joint effusion",
      "Crepitus present",
      "Muscle spasm",
      "Deformity present",
      "Distal neurovascular status intact",
    ],
  },
  {
    group: "Skin",
    items: [
      "Maculopapular rash",
      "Vesicular rash",
      "Urticarial lesions",
      "Cellulitis",
      "Abscess present",
      "Excoriations",
      "Scaling plaques",
      "Petechiae present",
      "Wound clean",
      "Wound discharge present",
    ],
  },
  {
    group: "Diabetes and vascular",
    items: [
      "Acanthosis nigricans",
      "Diabetic foot risk identified",
      "Protective sensation intact",
      "Protective sensation reduced",
      "Foot ulcer present",
      "Dorsalis pedis pulse palpable",
      "Postural blood pressure drop",
    ],
  },
];

export const diagnoses: CatalogGroup[] = [
  {
    group: "Respiratory and ENT",
    items: [
      "Viral upper respiratory tract infection",
      "Acute pharyngitis",
      "Acute tonsillitis",
      "Allergic rhinitis",
      "Acute rhinosinusitis",
      "Acute otitis media",
      "Otitis externa",
      "Acute bronchitis",
      "Community-acquired pneumonia",
      "Bronchial asthma",
      "Acute exacerbation of COPD",
    ],
  },
  {
    group: "Infectious and tropical",
    items: [
      "Acute febrile illness",
      "Dengue—suspected",
      "Dengue—confirmed",
      "Malaria—suspected",
      "Malaria—confirmed",
      "Enteric fever—suspected",
      "Chikungunya—suspected",
      "Leptospirosis—suspected",
      "Pulmonary tuberculosis—suspected",
      "COVID-19—suspected",
      "Influenza-like illness",
    ],
  },
  {
    group: "Gastrointestinal",
    items: [
      "Acute gastroenteritis",
      "Acute gastritis",
      "Gastroesophageal reflux disease",
      "Constipation",
      "Irritable bowel syndrome",
      "Haemorrhoids",
      "Anal fissure",
      "Fatty liver disease",
      "Food intolerance",
      "Dyspepsia",
    ],
  },
  {
    group: "Metabolic and endocrine",
    items: [
      "Type 2 diabetes mellitus",
      "Type 2 diabetes mellitus—uncontrolled",
      "Prediabetes",
      "Hypoglycaemia",
      "Hypothyroidism",
      "Hyperthyroidism",
      "Dyslipidaemia",
      "Obesity",
      "Vitamin D deficiency",
      "Vitamin B12 deficiency",
      "Iron deficiency anaemia",
    ],
  },
  {
    group: "Cardiovascular",
    items: [
      "Essential hypertension",
      "Hypertension—uncontrolled",
      "Postural hypotension",
      "Stable angina—suspected",
      "Cardiac arrhythmia—suspected",
      "Heart failure—suspected",
      "Peripheral arterial disease—suspected",
    ],
  },
  {
    group: "Neurological and mental health",
    items: [
      "Migraine",
      "Tension-type headache",
      "Benign paroxysmal positional vertigo",
      "Peripheral neuropathy",
      "Bell palsy",
      "Generalised anxiety symptoms",
      "Depressive symptoms",
      "Insomnia",
      "Acute stress reaction",
    ],
  },
  {
    group: "Musculoskeletal",
    items: [
      "Mechanical low back pain",
      "Cervical strain",
      "Muscle spasm",
      "Osteoarthritis of knee",
      "Shoulder tendinopathy",
      "Plantar fasciitis",
      "Ankle sprain",
      "Soft tissue injury",
      "Gout—suspected",
      "Inflammatory arthritis—suspected",
    ],
  },
  {
    group: "Urinary and reproductive",
    items: [
      "Lower urinary tract infection",
      "Pyelonephritis—suspected",
      "Renal colic—suspected",
      "Benign prostatic enlargement—suspected",
      "Vaginitis",
      "Pelvic inflammatory disease—suspected",
      "Dysmenorrhoea",
      "Abnormal uterine bleeding",
    ],
  },
  {
    group: "Skin",
    items: [
      "Contact dermatitis",
      "Atopic dermatitis",
      "Urticaria",
      "Tinea infection",
      "Scabies",
      "Bacterial cellulitis",
      "Furuncle",
      "Acne vulgaris",
      "Herpes zoster",
      "Insect-bite reaction",
    ],
  },
  {
    group: "Paediatrics",
    items: [
      "Acute respiratory infection in child",
      "Acute diarrhoeal disease in child",
      "Viral exanthem",
      "Hand foot and mouth disease",
      "Worm infestation",
      "Nutritional anaemia—suspected",
      "Growth faltering—suspected",
    ],
  },
  {
    group: "Emergency and referral",
    items: [
      "Acute coronary syndrome—suspected",
      "Stroke—suspected",
      "Meningitis—suspected",
      "Acute appendicitis—suspected",
      "Ectopic pregnancy—suspected",
      "Sepsis—suspected",
      "Anaphylaxis",
      "Hypertensive emergency—suspected",
    ],
  },
];

export const medicines: CatalogGroup[] = [
  {
    group: "Analgesics and antipyretics",
    items: [
      "Paracetamol 500 mg tablet",
      "Paracetamol 650 mg tablet",
      "Paracetamol 250 mg/5 mL suspension",
      "Ibuprofen 200 mg tablet",
      "Ibuprofen 400 mg tablet",
      "Diclofenac 50 mg tablet",
      "Diclofenac topical gel",
      "Naproxen 250 mg tablet",
    ],
  },
  {
    group: "Allergy and respiratory",
    items: [
      "Cetirizine 10 mg tablet",
      "Levocetirizine 5 mg tablet",
      "Fexofenadine 120 mg tablet",
      "Montelukast 10 mg tablet",
      "Salbutamol 100 mcg inhaler",
      "Budesonide 200 mcg inhaler",
      "Budesonide–formoterol inhaler",
      "Ipratropium nebuliser solution",
      "Fluticasone nasal spray",
    ],
  },
  {
    group: "Gastrointestinal",
    items: [
      "Pantoprazole 40 mg tablet",
      "Omeprazole 20 mg capsule",
      "Famotidine 20 mg tablet",
      "Ondansetron 4 mg tablet",
      "ORS low-osmolarity sachet",
      "Lactulose oral solution",
      "Bisacodyl 5 mg tablet",
      "Isabgol husk",
      "Dicyclomine 20 mg tablet",
      "Zinc 20 mg dispersible tablet",
    ],
  },
  {
    group: "Antibacterials",
    items: [
      "Amoxicillin 500 mg capsule",
      "Amoxicillin–clavulanate 625 mg tablet",
      "Azithromycin 500 mg tablet",
      "Cefixime 200 mg tablet",
      "Cefuroxime 500 mg tablet",
      "Doxycycline 100 mg capsule",
      "Nitrofurantoin 100 mg tablet",
      "Metronidazole 400 mg tablet",
      "Mupirocin 2% ointment",
    ],
  },
  {
    group: "Antifungal and antiparasitic",
    items: [
      "Fluconazole 150 mg tablet",
      "Clotrimazole 1% cream",
      "Terbinafine 1% cream",
      "Albendazole 400 mg tablet",
      "Ivermectin 6 mg tablet",
      "Permethrin 5% cream",
    ],
  },
  {
    group: "Diabetes",
    items: [
      "Metformin 500 mg tablet",
      "Metformin 1000 mg tablet",
      "Glimepiride 1 mg tablet",
      "Gliclazide MR 30 mg tablet",
      "Sitagliptin 100 mg tablet",
      "Empagliflozin 10 mg tablet",
      "Human soluble insulin 40 IU/mL",
      "Human isophane insulin 40 IU/mL",
    ],
  },
  {
    group: "Cardiovascular",
    items: [
      "Amlodipine 5 mg tablet",
      "Telmisartan 40 mg tablet",
      "Losartan 50 mg tablet",
      "Enalapril 5 mg tablet",
      "Metoprolol succinate 25 mg tablet",
      "Hydrochlorothiazide 12.5 mg tablet",
      "Atorvastatin 10 mg tablet",
      "Aspirin 75 mg tablet",
      "Clopidogrel 75 mg tablet",
    ],
  },
  {
    group: "Endocrine and supplements",
    items: [
      "Levothyroxine 25 mcg tablet",
      "Levothyroxine 50 mcg tablet",
      "Levothyroxine 75 mcg tablet",
      "Cholecalciferol 60,000 IU sachet",
      "Calcium carbonate 500 mg tablet",
      "Ferrous ascorbate tablet",
      "Folic acid 5 mg tablet",
      "Methylcobalamin 500 mcg tablet",
    ],
  },
  {
    group: "Dermatology",
    items: [
      "Calamine lotion",
      "Hydrocortisone 1% cream",
      "Mometasone 0.1% cream",
      "Benzoyl peroxide 2.5% gel",
      "Adapalene 0.1% gel",
      "Ketoconazole 2% shampoo",
      "Emollient cream",
    ],
  },
];

export const advice: CatalogGroup[] = [
  {
    group: "Hydration and nutrition",
    items: [
      "Maintain adequate oral hydration",
      "Use low-osmolarity oral rehydration solution",
      "Take a soft diet",
      "Avoid spicy and oily food",
      "Take small frequent meals",
      "Monitor oral intake",
      "Continue breastfeeding",
      "Follow diabetic meal plan",
    ],
  },
  {
    group: "Respiratory care",
    items: [
      "Warm saline gargles",
      "Steam inhalation with burn precautions",
      "Avoid smoke, dust and cold air",
      "Use mask in crowded spaces",
      "Voice rest",
      "Follow inhaler technique",
      "Monitor breathing difficulty",
    ],
  },
  {
    group: "Monitoring and safety-net",
    items: [
      "Record temperature",
      "Monitor blood pressure",
      "Monitor capillary blood glucose",
      "Monitor urine output",
      "Return urgently for breathing difficulty",
      "Return urgently for altered sensorium",
      "Return urgently for persistent vomiting",
      "Return urgently for bleeding",
      "Seek emergency care if symptoms worsen",
    ],
  },
  {
    group: "Recovery and follow-up",
    items: [
      "Rest as advised",
      "Maintain sleep routine",
      "Bring previous prescriptions and reports",
      "Review in 24 hours",
      "Review in 48 hours",
      "Review in 3 days",
      "Review in 7 days",
      "Follow up after investigations",
      "Gradually resume activity",
    ],
  },
  {
    group: "Lifestyle and prevention",
    items: [
      "Daily walking as tolerated",
      "Weight monitoring",
      "Salt restriction",
      "Stop tobacco use",
      "Limit alcohol",
      "Hand hygiene",
      "Mosquito-bite prevention",
      "Foot care for diabetes",
      "Stress-management practice",
    ],
  },
  {
    group: "Medicine use",
    items: [
      "Take medicines exactly as prescribed",
      "Complete antibiotic course if prescribed",
      "Do not share medicines",
      "Bring medicine strips at follow-up",
      "Stop medicine and seek care for allergic reaction",
      "Use spacer with inhaler",
      "Avoid self-medication",
    ],
  },
];

export const investigations: CatalogGroup[] = [
  {
    group: "Haematology",
    items: [
      "Complete blood count",
      "Peripheral blood smear",
      "Erythrocyte sedimentation rate",
      "Reticulocyte count",
      "Prothrombin time and INR",
      "Activated partial thromboplastin time",
    ],
  },
  {
    group: "Diabetes and metabolic",
    items: [
      "Fasting plasma glucose",
      "Postprandial plasma glucose",
      "Random plasma glucose",
      "HbA1c",
      "Serum electrolytes",
      "Serum calcium",
      "Serum uric acid",
      "Vitamin B12 level",
      "25-hydroxy vitamin D",
    ],
  },
  {
    group: "Renal and urine",
    items: [
      "Serum creatinine with eGFR",
      "Blood urea nitrogen",
      "Urine routine and microscopy",
      "Urine albumin-creatinine ratio",
      "Urine culture and sensitivity",
      "24-hour urine protein",
    ],
  },
  {
    group: "Liver and gastrointestinal",
    items: [
      "Liver function tests",
      "Serum amylase",
      "Serum lipase",
      "Stool routine and microscopy",
      "Stool occult blood",
      "H. pylori test",
    ],
  },
  {
    group: "Thyroid and lipids",
    items: [
      "Thyroid-stimulating hormone",
      "Free T4",
      "Free T3",
      "Lipid profile",
    ],
  },
  {
    group: "Infectious and tropical",
    items: [
      "Malaria rapid diagnostic test",
      "Peripheral smear for malaria parasite",
      "Dengue NS1 antigen",
      "Dengue IgM antibody",
      "Chikungunya IgM antibody",
      "Blood culture",
      "Widal test",
      "HIV-1 and HIV-2 screening",
      "HBsAg",
      "Anti-HCV antibody",
      "Sputum test for tuberculosis",
    ],
  },
  {
    group: "Inflammation and autoimmune",
    items: [
      "C-reactive protein",
      "Rheumatoid factor",
      "Anti-CCP antibody",
      "Antinuclear antibody",
    ],
  },
  {
    group: "Cardiac",
    items: [
      "12-lead ECG",
      "Troponin",
      "2D echocardiography",
      "24-hour Holter monitoring",
      "Exercise stress test",
    ],
  },
  {
    group: "Imaging",
    items: [
      "Chest X-ray PA view",
      "X-ray affected joint",
      "Ultrasound abdomen and pelvis",
      "Ultrasound KUB",
      "CT brain",
      "CT chest",
      "MRI affected region",
    ],
  },
  {
    group: "Point-of-care and monitoring",
    items: [
      "Capillary blood glucose",
      "Pulse oximetry",
      "Peak expiratory flow",
      "Ambulatory blood pressure monitoring",
      "Orthostatic blood pressure",
      "Urine pregnancy test",
    ],
  },
];

export const ingredientByMedicine: Record<string, string> = {
  "Paracetamol 500 mg tablet": "Paracetamol IP 500 mg",
  "Paracetamol 650 mg tablet": "Paracetamol IP 650 mg",
  "Levocetirizine 5 mg tablet": "Levocetirizine dihydrochloride 5 mg",
  "Pantoprazole 40 mg tablet": "Pantoprazole sodium equivalent to 40 mg",
  "Azithromycin 500 mg tablet": "Azithromycin dihydrate equivalent to 500 mg",
  "Metformin 500 mg tablet": "Metformin hydrochloride 500 mg",
};
